set_property SRC_FILE_INFO {cfile:{d:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/01_ibert_loopback/Vivado/ibert_ultrascale_gth_0_ex.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0.xdc} rfile:../../../ibert_ultrascale_gth_0_ex.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0.xdc id:1 order:EARLY scoped_inst:u_ibert_gth_core/inst} [current_design]
set_property SRC_FILE_INFO {cfile:{d:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/01_ibert_loopback/Vivado/ibert_ultrascale_gth_0_ex.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/attributes.xdc} rfile:../../../ibert_ultrascale_gth_0_ex.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/attributes.xdc id:2 order:EARLY scoped_inst:u_ibert_gth_core/inst} [current_design]
set_property SRC_FILE_INFO {cfile:{D:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/01_ibert_loopback/Vivado/imports/example_ibert_ultrascale_gth_0.xdc} rfile:../../../imports/example_ibert_ultrascale_gth_0.xdc id:3} [current_design]
current_instance u_ibert_gth_core/inst
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y4 [get_cells QUAD[0].u_q/CH[0].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y5 [get_cells QUAD[0].u_q/CH[1].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y6 [get_cells QUAD[0].u_q/CH[2].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y7 [get_cells QUAD[0].u_q/CH[3].u_ch/u_gthe4_channel]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_COMMON_X0Y1 [get_cells QUAD[0].u_q/u_common/u_gthe4_common]
set_property src_info {type:SCOPED_XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/TXRATE[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/RXRATE[*]}]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[0].u_q/CH[*].u_ch/u_gthe4_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/TXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/RXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/RXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[*].u_q/CH[*].u_ch/u_gthe4_channel/RXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD2[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {QUAD[0].u_q/u_common/u_gthe4_common/QPLLRSVD3[4]}]
current_instance
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 156250000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports gth_refclk0p_i[0]]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y5 [get_ports gth_refclk0n_i[0]]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports gth_refclk1p_i[0]]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports gth_refclk1n_i[0]]
