# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ddr_axis/ddr_axis.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_axis || ORIG_REF_NAME==ddr_axis} -quiet] -quiet

# IP: bd/ddr_axis/ip/ddr_axis_zynq_ultra_ps_e_0_0/ddr_axis_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_axis_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ddr_axis_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ddr_axis/ip/ddr_axis_proc_sys_reset_0_0/ddr_axis_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_axis_proc_sys_reset_0_0 || ORIG_REF_NAME==ddr_axis_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/ddr_axis_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_axis_smartconnect_0_0 || ORIG_REF_NAME==ddr_axis_smartconnect_0_0} -quiet] -quiet

# Block Designs: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/bd_0fb6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_0/bd_0fb6_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_1/bd_0fb6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_2/bd_0fb6_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_3/bd_0fb6_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_4/bd_0fb6_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_5/bd_0fb6_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_6/bd_0fb6_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_7/bd_0fb6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_8/bd_0fb6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_9/bd_0fb6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_10/bd_0fb6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_11/bd_0fb6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_12/bd_0fb6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_13/bd_0fb6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_14/bd_0fb6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_15/bd_0fb6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_16/bd_0fb6_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_17/bd_0fb6_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_18/bd_0fb6_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_19/bd_0fb6_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_20/bd_0fb6_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_21/bd_0fb6_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_22/bd_0fb6_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_23/bd_0fb6_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_24/bd_0fb6_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_25/bd_0fb6_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_26/bd_0fb6_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_27/bd_0fb6_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_28/bd_0fb6_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_29/bd_0fb6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_30/bd_0fb6_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_31/bd_0fb6_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_32/bd_0fb6_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_33/bd_0fb6_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_34/bd_0fb6_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_35/bd_0fb6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_36/bd_0fb6_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_37/bd_0fb6_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_38/bd_0fb6_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_39/bd_0fb6_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_40/bd_0fb6_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_41/bd_0fb6_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_42/bd_0fb6_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/ddr_axis/ip/ddr_axis_axi_dma_0_0/ddr_axis_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_axis_axi_dma_0_0 || ORIG_REF_NAME==ddr_axis_axi_dma_0_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_zynq_ultra_ps_e_0_0/ddr_axis_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_zynq_ultra_ps_e_0_0/ddr_axis_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_axis_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ddr_axis_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_proc_sys_reset_0_0/ddr_axis_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_axis_proc_sys_reset_0_0 || ORIG_REF_NAME==ddr_axis_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_proc_sys_reset_0_0/ddr_axis_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_axis_proc_sys_reset_0_0 || ORIG_REF_NAME==ddr_axis_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_1/bd_0fb6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_1/bd_0fb6_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_2/bd_0fb6_arsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_3/bd_0fb6_rsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_4/bd_0fb6_awsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_5/bd_0fb6_wsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_6/bd_0fb6_bsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_10/bd_0fb6_s00a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_11/bd_0fb6_sarn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_12/bd_0fb6_srn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_13/bd_0fb6_sawn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_14/bd_0fb6_swn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_15/bd_0fb6_sbn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_19/bd_0fb6_s01a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_20/bd_0fb6_sarn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_21/bd_0fb6_srn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_25/bd_0fb6_s02a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_26/bd_0fb6_sawn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_27/bd_0fb6_swn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_28/bd_0fb6_sbn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_29/bd_0fb6_m00s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_30/bd_0fb6_m00arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_31/bd_0fb6_m00rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_32/bd_0fb6_m00awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_33/bd_0fb6_m00wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_34/bd_0fb6_m00bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_36/bd_0fb6_m01s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_37/bd_0fb6_m01arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_38/bd_0fb6_m01rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_39/bd_0fb6_m01awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_40/bd_0fb6_m01wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/bd_0/ip/ip_41/bd_0fb6_m01bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_smartconnect_0_0/ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_axi_dma_0_0/ddr_axis_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_axis_axi_dma_0_0 || ORIG_REF_NAME==ddr_axis_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ip/ddr_axis_axi_dma_0_0/ddr_axis_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_axis_axi_dma_0_0 || ORIG_REF_NAME==ddr_axis_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/Internet_UDP/02_udp_axi_stream_loopback/Vivado/02_udp_axi_stream_loopback.gen/sources_1/bd/ddr_axis/ddr_axis_ooc.xdc
