# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/w25q64_controller.xdc

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/vio_0/vio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/ila_1/ila_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/ila_0/ila_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/vio_0/vio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SPI/05_w25q64_controller/Vivado/05_w25q64_controller.gen/sources_1/ip/ila_1/ila_1_ooc.xdc
