# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8679_eth_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8679_eth_buf_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_0/synth/bd_8679_eth_buf_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8679_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8679_eth_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8679_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8679_eth_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8679_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_0/synth/bd_8679_eth_buf_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8679_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8679_eth_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8679_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
