# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ddr_block_design/ddr_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_block_design || ORIG_REF_NAME==ddr_block_design} -quiet] -quiet

# IP: bd/ddr_block_design/ip/ddr_block_design_zynq_ultra_ps_e_0_0/ddr_block_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_block_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ddr_block_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ddr_block_design/ip/ddr_block_design_proc_sys_reset_0_0/ddr_block_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_block_design_proc_sys_reset_0_0 || ORIG_REF_NAME==ddr_block_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ddr_block_design/ip/ddr_block_design_smartconnect_0_0/ddr_block_design_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_block_design_smartconnect_0_0 || ORIG_REF_NAME==ddr_block_design_smartconnect_0_0} -quiet] -quiet

# IP: bd/ddr_block_design/ip/ddr_block_design_axi_dma_0_0/ddr_block_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_block_design_axi_dma_0_0 || ORIG_REF_NAME==ddr_block_design_axi_dma_0_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/DDR/ddr_axi_dma_stream_processor/ddr_axi_dma_stream_processor.gen/sources_1/bd/ddr_block_design/ddr_block_design_ooc.xdc
