# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.srcs/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0.xci
# IP: The module: 'udp_parser_in_pl_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.srcs/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0.xci
# IP: The module: 'udp_parser_in_pl_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
