# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_mac_cons.xdc

# Block Designs: bd/eth_mac_loopback/eth_mac_loopback.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_loopback || ORIG_REF_NAME==eth_mac_loopback} -quiet] -quiet

# IP: bd/eth_mac_loopback/ip/eth_mac_loopback_zynq_ultra_ps_e_0_0/eth_mac_loopback_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_loopback_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==eth_mac_loopback_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/eth_mac_loopback/ip/eth_mac_loopback_proc_sys_reset_0_0/eth_mac_loopback_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_loopback_proc_sys_reset_0_0 || ORIG_REF_NAME==eth_mac_loopback_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/eth_mac_loopback_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_loopback_smartconnect_0_0 || ORIG_REF_NAME==eth_mac_loopback_smartconnect_0_0} -quiet] -quiet

# Block Designs: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/bd_4aa7.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_0/bd_4aa7_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_1/bd_4aa7_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_2/bd_4aa7_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_3/bd_4aa7_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_4/bd_4aa7_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_5/bd_4aa7_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_6/bd_4aa7_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_7/bd_4aa7_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_8/bd_4aa7_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_9/bd_4aa7_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_10/bd_4aa7_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_11/bd_4aa7_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_12/bd_4aa7_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_13/bd_4aa7_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_14/bd_4aa7_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_15/bd_4aa7_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_16/bd_4aa7_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_17/bd_4aa7_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_18/bd_4aa7_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_19/bd_4aa7_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_20/bd_4aa7_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_21/bd_4aa7_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_22/bd_4aa7_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_23/bd_4aa7_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_24/bd_4aa7_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_25/bd_4aa7_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_26/bd_4aa7_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_27/bd_4aa7_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_28/bd_4aa7_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_29/bd_4aa7_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_30/bd_4aa7_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_31/bd_4aa7_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_32/bd_4aa7_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/eth_mac_loopback/ip/eth_mac_loopback_clk_wiz_0_0/eth_mac_loopback_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_loopback_clk_wiz_0_0 || ORIG_REF_NAME==eth_mac_loopback_clk_wiz_0_0} -quiet] -quiet

# IP: bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/eth_mac_loopback_axi_ethernet_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eth_mac_loopback_axi_ethernet_1_0 || ORIG_REF_NAME==eth_mac_loopback_axi_ethernet_1_0} -quiet] -quiet

# Block Designs: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/bd_50c1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_50c1 || ORIG_REF_NAME==bd_50c1} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_0/bd_50c1_eth_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_50c1_eth_buf_0 || ORIG_REF_NAME==bd_50c1_eth_buf_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_1/bd_50c1_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_50c1_mac_0 || ORIG_REF_NAME==bd_50c1_mac_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_2/bd_50c1_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_50c1_c_shift_ram_0_0 || ORIG_REF_NAME==bd_50c1_c_shift_ram_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_3/bd_50c1_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_50c1_c_counter_binary_0_0 || ORIG_REF_NAME==bd_50c1_c_counter_binary_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_4/bd_50c1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_50c1_xlconstant_0_0 || ORIG_REF_NAME==bd_50c1_xlconstant_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_5/bd_50c1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_50c1_util_vector_logic_0_0 || ORIG_REF_NAME==bd_50c1_util_vector_logic_0_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_zynq_ultra_ps_e_0_0/eth_mac_loopback_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_zynq_ultra_ps_e_0_0/eth_mac_loopback_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==eth_mac_loopback_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==eth_mac_loopback_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_proc_sys_reset_0_0/eth_mac_loopback_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==eth_mac_loopback_proc_sys_reset_0_0 || ORIG_REF_NAME==eth_mac_loopback_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_proc_sys_reset_0_0/eth_mac_loopback_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==eth_mac_loopback_proc_sys_reset_0_0 || ORIG_REF_NAME==eth_mac_loopback_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_1/bd_4aa7_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_1/bd_4aa7_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_2/bd_4aa7_arinsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_3/bd_4aa7_rinsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_4/bd_4aa7_awinsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_5/bd_4aa7_winsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_6/bd_4aa7_binsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_7/bd_4aa7_aroutsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_8/bd_4aa7_routsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_9/bd_4aa7_awoutsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_10/bd_4aa7_woutsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_11/bd_4aa7_boutsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_12/bd_4aa7_arni_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_13/bd_4aa7_rni_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_14/bd_4aa7_awni_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_15/bd_4aa7_wni_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_16/bd_4aa7_bni_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_20/bd_4aa7_s00a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_21/bd_4aa7_sarn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_22/bd_4aa7_srn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_23/bd_4aa7_sawn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_24/bd_4aa7_swn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_25/bd_4aa7_sbn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_26/bd_4aa7_m00s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_27/bd_4aa7_m00arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_28/bd_4aa7_m00rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_29/bd_4aa7_m00awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_30/bd_4aa7_m00wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/bd_0/ip/ip_31/bd_4aa7_m00bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_smartconnect_0_0/ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_clk_wiz_0_0/eth_mac_loopback_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==eth_mac_loopback_clk_wiz_0_0 || ORIG_REF_NAME==eth_mac_loopback_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_clk_wiz_0_0/eth_mac_loopback_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==eth_mac_loopback_clk_wiz_0_0 || ORIG_REF_NAME==eth_mac_loopback_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_clk_wiz_0_0/eth_mac_loopback_clk_wiz_0_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_0/bd_50c1_eth_buf_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_50c1_eth_buf_0 || ORIG_REF_NAME==bd_50c1_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_0/synth/bd_50c1_eth_buf_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_50c1_eth_buf_0 || ORIG_REF_NAME==bd_50c1_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_50c1_mac_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_50c1_mac_0 || ORIG_REF_NAME==bd_50c1_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_50c1_mac_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_50c1_mac_0 || ORIG_REF_NAME==bd_50c1_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_50c1_mac_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_50c1_mac_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_50c1_mac_0 || ORIG_REF_NAME==bd_50c1_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/bd_0/bd_50c1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/eth_mac_loopback_axi_ethernet_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==eth_mac_loopback_axi_ethernet_1_0 || ORIG_REF_NAME==eth_mac_loopback_axi_ethernet_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/synth/eth_mac_loopback_axi_ethernet_1_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/ip/eth_mac_loopback_axi_ethernet_1_0/synth/eth_mac_loopback_axi_ethernet_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==eth_mac_loopback_axi_ethernet_1_0 || ORIG_REF_NAME==eth_mac_loopback_axi_ethernet_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/01_eth_mac_loopback/Vivado/01_eth_mac_loopback.gen/sources_1/bd/eth_mac_loopback/eth_mac_loopback_ooc.xdc
