# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_mac_cons.xdc

# Block Designs: bd/udp_parser_in_pl/udp_parser_in_pl.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==udp_parser_in_pl || ORIG_REF_NAME==udp_parser_in_pl} -quiet] -quiet

# IP: bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/udp_parser_in_pl_axi_ethernet_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==udp_parser_in_pl_axi_ethernet_1_0 || ORIG_REF_NAME==udp_parser_in_pl_axi_ethernet_1_0} -quiet] -quiet

# IP: bd/udp_parser_in_pl/ip/udp_parser_in_pl_clk_wiz_0_0/udp_parser_in_pl_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==udp_parser_in_pl_clk_wiz_0_0 || ORIG_REF_NAME==udp_parser_in_pl_clk_wiz_0_0} -quiet] -quiet

# IP: bd/udp_parser_in_pl/ip/udp_parser_in_pl_proc_sys_reset_0_0/udp_parser_in_pl_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==udp_parser_in_pl_proc_sys_reset_0_0 || ORIG_REF_NAME==udp_parser_in_pl_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/udp_parser_in_pl/ip/udp_parser_in_pl_smartconnect_0_0/udp_parser_in_pl_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==udp_parser_in_pl_smartconnect_0_0 || ORIG_REF_NAME==udp_parser_in_pl_smartconnect_0_0} -quiet] -quiet

# IP: bd/udp_parser_in_pl/ip/udp_parser_in_pl_system_ila_0_0/udp_parser_in_pl_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==udp_parser_in_pl_system_ila_0_0 || ORIG_REF_NAME==udp_parser_in_pl_system_ila_0_0} -quiet] -quiet

# IP: bd/udp_parser_in_pl/ip/udp_parser_in_pl_zynq_ultra_ps_e_0_0/udp_parser_in_pl_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==udp_parser_in_pl_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==udp_parser_in_pl_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/udp_parser_in_pl/ip/udp_parser_in_pl_udp_parser_0_0/udp_parser_in_pl_udp_parser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==udp_parser_in_pl_udp_parser_0_0 || ORIG_REF_NAME==udp_parser_in_pl_udp_parser_0_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/udp_parser_in_pl_ooc.xdc
