# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.srcs/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/udp_parser_in_pl_axi_ethernet_1_0.xci
# IP: The module: 'udp_parser_in_pl_axi_ethernet_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/bd_8679.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679 || ORIG_REF_NAME==bd_8679} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8679_eth_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_eth_buf_0 || ORIG_REF_NAME==bd_8679_eth_buf_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_1/bd_8679_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_mac_0 || ORIG_REF_NAME==bd_8679_mac_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_2/bd_8679_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_c_shift_ram_0_0 || ORIG_REF_NAME==bd_8679_c_shift_ram_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_3/bd_8679_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_c_counter_binary_0_0 || ORIG_REF_NAME==bd_8679_c_counter_binary_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_4/bd_8679_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_xlconstant_0_0 || ORIG_REF_NAME==bd_8679_xlconstant_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_5/bd_8679_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_util_vector_logic_0_0 || ORIG_REF_NAME==bd_8679_util_vector_logic_0_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/bd_8679_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/udp_parser_in_pl_axi_ethernet_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/synth/udp_parser_in_pl_axi_ethernet_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/synth/udp_parser_in_pl_axi_ethernet_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.srcs/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/udp_parser_in_pl_axi_ethernet_1_0.xci
# IP: The module: 'udp_parser_in_pl_axi_ethernet_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/bd_8679.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679 || ORIG_REF_NAME==bd_8679} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8679_eth_buf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_eth_buf_0 || ORIG_REF_NAME==bd_8679_eth_buf_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_1/bd_8679_mac_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_mac_0 || ORIG_REF_NAME==bd_8679_mac_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_2/bd_8679_c_shift_ram_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_c_shift_ram_0_0 || ORIG_REF_NAME==bd_8679_c_shift_ram_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_3/bd_8679_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_c_counter_binary_0_0 || ORIG_REF_NAME==bd_8679_c_counter_binary_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_4/bd_8679_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_xlconstant_0_0 || ORIG_REF_NAME==bd_8679_xlconstant_0_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/ip/ip_5/bd_8679_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8679_util_vector_logic_0_0 || ORIG_REF_NAME==bd_8679_util_vector_logic_0_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/bd_0/bd_8679_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/udp_parser_in_pl_axi_ethernet_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/synth/udp_parser_in_pl_axi_ethernet_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/PL Ethernet/03_udp_parser_in_pl/Vivado/udp_parser_in_pl.gen/sources_1/bd/udp_parser_in_pl/ip/udp_parser_in_pl_axi_ethernet_1_0/synth/udp_parser_in_pl_axi_ethernet_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_parser_in_pl_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
