# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/02_sfp_external_loopback/Vivado/imports/example_ibert_ultrascale_gth_0.xdc

# XDC: D:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/02_sfp_external_loopback/Vivado/imports/ibert_ultrascale_gth_ip_example.xdc

# IP: ip/ibert_ultrascale_gth_0/ibert_ultrascale_gth_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ibert_ultrascale_gth_0 || ORIG_REF_NAME==ibert_ultrascale_gth_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/02_sfp_external_loopback/Vivado/ibert_ultrascale_gth_0_ex.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/02_sfp_external_loopback/Vivado/ibert_ultrascale_gth_0_ex.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/ibert_ultrascale_gth_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ibert_ultrascale_gth_0 || ORIG_REF_NAME==ibert_ultrascale_gth_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/02_sfp_external_loopback/Vivado/ibert_ultrascale_gth_0_ex.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/sw_mcs_all.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ibert_ultrascale_gth_0 || ORIG_REF_NAME==ibert_ultrascale_gth_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/INTERFACE/SFP GT BERT/02_sfp_external_loopback/Vivado/ibert_ultrascale_gth_0_ex.gen/sources_1/ip/ibert_ultrascale_gth_0/synth/attributes.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ibert_ultrascale_gth_0 || ORIG_REF_NAME==ibert_ultrascale_gth_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
